### ISSUE TITLE
universe inconsistency

### ISSUE THREAD

**Issue by vzaliva** [coq-ext-lib/coq-ext-lib#23] opened 2016-04-25 22:14 UTC
I am porting my code from Coq-8.4 to Coq-8.5pl1 and encountered the following problem:

```
Section WriterMonad.
  Variable s t : Type.
  Variable Monoid_s : Monoid s.
  
  Definition writer := writerT Monoid_s ident.
  Definition runWriter x := unIdent (@runWriterT s Monoid_s ident t x).
  Definition execWriter x:= snd (runWriter x).
  Definition evalWriter x:= fst (runWriter x).
End WriterMonad.

Definition Monoid_RthetaFlags : ExtLib.Structures.Monoid.Monoid RthetaFlags := ExtLib.Structures.Monoid.Build_Monoid RthetaFlagsAppend RthetaFlagsZero.

Definition flags_m : Type -> Type := writer Monoid_RthetaFlags.

```

Trying to compile the example above gives me the following error:

```
Error:
The term "Monoid_RthetaFlags" has type "Monoid.Monoid RthetaFlags"
while it is expected to have type "Monoid.Monoid ?s"
(universe inconsistency).
Makefile:274: recipe for target 'Rtheta.vo' failed

```

Any suggestions what might be causing this and what are possible workarounds? The code I have provided above is abridged, but if needed I can extract full self-containing example. Thanks!

**Comment by gmalecha** [comment] 2016-04-25 22:17
It looks like a universe problem. Generally those are kind of difficult to debug but they also rarely crop up when "simple" things are going on. I don't think that I can debug this without a more complete example. If there is a place where I can see the code, I can take a look.

**Comment by vzaliva** [comment] 2016-04-25 22:26
I am attaching self-contained example. Last line of R.v gives the error shown above.

[Rtheta.txt](https://github.com/coq-ext-lib/coq-ext-lib/files/235521/Rtheta.txt)
[WriterMonadNoT.txt](https://github.com/coq-ext-lib/coq-ext-lib/files/235522/WriterMonadNoT.txt)

Thanks!

**Comment by gmalecha** [comment] 2016-04-25 23:20
It looks like the issue is with the fact that the writerT is not universe polymorphic. I can fix that in ExtLib and build a new package.

**Comment by vzaliva** [comment] 2016-04-26 00:10
Thanks for looking into it and I am looking forward to the fix.

**Comment by gmalecha** [comment] 2016-04-26 00:59
This is fixed in ff0e272a0ff6e5db11f6f48475d6168c17e2c950.

**Comment by vzaliva** [comment] 2016-04-26 01:03
Thanks! How soon do you think this fix will propagate to OPAM repository? I would rather avoid installing it manually.

**Comment by gmalecha** [comment] 2016-04-26 01:05
I will submit a pull request tonight.

**Comment by gmalecha** [comment] 2016-04-26 04:14
Pull request submitted. https://github.com/coq/opam-coq-archive/pull/63

**Closed by gmalecha** 2016-04-26 04:14 UTC
Labels: universes

**Comment by vzaliva** [comment] 2016-04-26 18:48
After this patch _WriterMonadNoT.v_ no longer compiles:

```
File "./WriterMonadNoT.v", line 18, characters 33-44:
Error:
In environment
s, t : Type
Monoid_s : Monoid s
x : writerT Monoid_s ident t
The term "runWriter x" has type "PPair.pprod t s"
while it is expected to have type "(?A * ?B)%type".
make: *** [WriterMonadNoT.vo] Error 1
```

**Comment by gmalecha** [comment] 2016-04-26 18:52
In order to (partially) break the dependence on pairs (which introduces some universe constraints), I needed to implement the writer monad using polymorphic pairs. They work essentially the same way as regular pairs except they are polymorphic and use primitive projections (and are therefore more efficient).

**Comment by vzaliva** [comment] 2016-04-26 21:45
I have changed in WriterMonadNoT in my example above 'fst' to 'pfst' and 'snd' to 'psnd' after which it compiled without the problem. However the original error still persists:

```
The term "Monoid_RthetaFlags" has type "Monoid.Monoid RthetaFlags"
while it is expected to have type "Monoid.Monoid ?s" (universe inconsistency).
```

Here is the line which triggers it:

`Definition flags_m : Type -> Type := writer Monoid_RthetaFlags.
`

**Comment by gmalecha** [comment] 2016-04-26 21:57
Hmmm...it is working for me. Here are the two files that you sent me.

[WriterMonadNoT.txt](https://github.com/coq-ext-lib/coq-ext-lib/files/237579/WriterMonadNoT.txt)
[Rtheta.txt](https://github.com/coq-ext-lib/coq-ext-lib/files/237580/Rtheta.txt)

**Comment by vzaliva** [comment] 2016-04-26 22:17
Sorry, I did not realized I need not specify:

`Set Universe Polymorphism.`

It solved the problem. Thanks!

**Comment by gmalecha** [comment] 2016-04-26 22:20
Ah. I should have pointed that out. U had forgotten that that was the first
thing that I did.

On Tue, Apr 26, 2016, 3:17 PM Vadim Zaliva <notifications@github.com> wrote:

> Sorry, I did not realized I need not specify:
>
> Set Universe Polymorphism.
>
> It solved the problem. Thanks!
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/coq-ext-lib/coq-ext-lib/issues/23#issuecomment-214904718>
>
-- 

- gregory malecha
  gmalecha.github.io
